name: meedu_lints
description: Dart lint rules for flutter_meedu
version: 0.1.0
repository: https://github.com/darwin-morocho/flutter-meedu

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  analyzer: ^7.0.0
  analyzer_plugin: ^0.12.0
  custom_lint_builder: ^0.7.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
