name: flutter_meedu
description: A powerful State Management, Dependency Injection, Reactive programming and Navigation for Flutter apps.
version: 9.0.2
homepage: https://github.com/darwin-morocho/flutter-meedu/tree/master/packages/flutter_meedu
documentation: https://flutter.meedu.app

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  equatable: ^2.0.5
  flutter_test:
    sdk: flutter