name: flutter_meedu
description: A simple State Managment, Dependency Injection, Reactive programming and Navigation for Flutter apps.
version: 3.0.10
homepage: https://github.com/darwin-morocho/flutter-meedu/tree/master/packages/flutter_meedu
documentation: https://flutter.meedu.app

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # meedu: ^3.0.8
  # meedu:
  #   path: ../meedu

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^2.0.0