name: flutter_meedu
description: A powerful State Management, Dependency Injection, Reactive programming and Navigation for Flutter apps.
version: 9.2.1
homepage: https://github.com/darwin-morocho/flutter-meedu/tree/master/packages/flutter_meedu
documentation: https://flutter.meedu.app

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  meedu: ^9.3.1
  # meedu:
  #   path: ../meedu

dev_dependencies:
  equatable: ^2.0.7
  flutter_test:
    sdk: flutter