name: flutter_meedu
description: A powerful State Management, Dependency Injection, Reactive programming and Navigation for Flutter apps.
version: 5.3.1
homepage: https://github.com/darwin-morocho/flutter-meedu/tree/master/packages/flutter_meedu
documentation: https://flutter.meedu.app

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meedu: ^4.3.0


  # meedu:
  #   path: ../meedu

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^2.0.0